name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Run tests
      env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASS: ${{secrets.DB_PASS}}
          DB_PORT: ${{secrets.DB_PORT}}
    - name: Fetch latest data
      run: |-
        python3 monitor.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
